# Generated by Django 4.0.4 on 2022-11-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop3', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
