# Generated by Django 4.1 on 2022-11-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartitem_active_alter_cart_cart_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
